export const short = {
  en_US: 'No longer maintained. Cloud data storage and sharing',
  es_ES:
    'Ya sin mantenimiento. Almacenamiento y compartición de datos en la nube',
  de_DE: 'Nicht mehr gepflegt. Cloud-Datenspeicherung und -freigabe',
  pl_PL: 'Bez wsparcia. Przechowywanie i udostępnianie danych w chmurze',
  fr_FR: 'Non maintenu. Stockage et partage de données cloud',
}

export const long = {
  en_US:
    'File Browser is no longer maintained. Its developers have ended the project: there will be no further releases and no security fixes, and installing it today means adopting software nobody is repairing. Choose FileBrowser Quantum, copyparty, or NextExplorer instead — all three are in this marketplace and actively developed. FileBrowser Quantum is a maintained fork of this very project and is offered under this same listing as a separate flavor, so existing users can switch to it and keep their files, accounts, and passwords. What File Browser does, for as long as you run it: a simple file managing interface to upload, download, organize, edit, and share your files, with multiple users who can each have their own directory.',
  es_ES:
    'File Browser ya no recibe mantenimiento. Sus desarrolladores han dado por terminado el proyecto: no habrá más versiones ni correcciones de seguridad, e instalarlo hoy significa adoptar software que nadie repara. Elige en su lugar FileBrowser Quantum, copyparty o NextExplorer: los tres están en este mercado y se desarrollan activamente. FileBrowser Quantum es una bifurcación mantenida de este mismo proyecto y se ofrece en esta misma ficha como una variante distinta, así que quienes ya lo usan pueden cambiar a ella y conservar sus archivos, cuentas y contraseñas. Lo que hace File Browser, mientras lo sigas usando: una interfaz simple de gestión de archivos para cargar, descargar, organizar, editar y compartir tus archivos, con varios usuarios que pueden tener cada uno su propio directorio.',
  de_DE:
    'File Browser wird nicht mehr gepflegt. Die Entwickler haben das Projekt beendet: es wird keine weiteren Versionen und keine Sicherheitsupdates geben, und wer es heute installiert, übernimmt Software, die niemand repariert. Wählen Sie stattdessen FileBrowser Quantum, copyparty oder NextExplorer — alle drei sind in diesem Marktplatz und werden aktiv entwickelt. FileBrowser Quantum ist eine gepflegte Abspaltung genau dieses Projekts und wird unter diesem Eintrag als eigene Variante angeboten, sodass bestehende Nutzer wechseln und ihre Dateien, Konten und Passwörter behalten können. Was File Browser leistet, solange Sie es betreiben: eine einfache Dateiverwaltungsoberfläche zum Hochladen, Herunterladen, Organisieren, Bearbeiten und Teilen Ihrer Dateien, mit mehreren Benutzern, die jeweils ein eigenes Verzeichnis haben können.',
  pl_PL:
    'File Browser nie jest już rozwijany. Twórcy zakończyli projekt: nie będzie kolejnych wydań ani poprawek bezpieczeństwa, a instalacja dzisiaj oznacza przyjęcie oprogramowania, którego nikt nie naprawia. Wybierz zamiast tego FileBrowser Quantum, copyparty lub NextExplorer — wszystkie trzy są w tym sklepie i są aktywnie rozwijane. FileBrowser Quantum to utrzymywana odnoga tego samego projektu, oferowana w tej samej pozycji jako osobny wariant, więc dotychczasowi użytkownicy mogą się na nią przenieść i zachować swoje pliki, konta i hasła. Co robi File Browser, dopóki z niego korzystasz: prosty interfejs zarządzania plikami do przesyłania, pobierania, organizowania, edytowania i udostępniania plików, z wieloma użytkownikami, z których każdy może mieć własny katalog.',
  fr_FR:
    "File Browser n'est plus maintenu. Ses développeurs ont mis fin au projet : il n'y aura plus de versions ni de correctifs de sécurité, et l'installer aujourd'hui revient à adopter un logiciel que personne ne répare. Choisissez plutôt FileBrowser Quantum, copyparty ou NextExplorer — les trois sont sur cette place de marché et activement développés. FileBrowser Quantum est une bifurcation maintenue de ce projet même et est proposé sous cette même fiche comme une variante distincte, si bien que les utilisateurs actuels peuvent y basculer en conservant leurs fichiers, comptes et mots de passe. Ce que fait File Browser, tant que vous l'utilisez : une interface simple de gestion de fichiers pour téléverser, télécharger, organiser, modifier et partager vos fichiers, avec plusieurs utilisateurs pouvant chacun disposer de leur propre répertoire.",
}
